runtime: nodejs8
instance_class: F1
service: datank-poll
automatic_scaling:
  max_instances: 1
env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
